library(shiny)
library(shinydashboard)
library(shinythemes)
library(shinyWidgets)
library(shinyjs) 

library(lattice)
library(ggplot2)
library(ggiraph)
library(tools)
library(DT)
library(RcmdrMisc)
library(car)
library(lmtest)
library(outliers)
library(MESS)
library(pwr)

options(warn = -1)
options(shiny.maxRequestSize = 30 * 1024 ^ 2)

