header<-dashboardHeader(title = "MODUNIVAR",
                        tags$li(actionLink("openModal", label = "", 
                                           icon = icon("address-card")),
                                class = "dropdown"))

sidebar<- dashboardSidebar(
    sidebarMenu(
                menuItem(text = "Dati",icon = shiny::icon("file-text"),
                  menuSubItem("Esempi Master",tabName = "esempi"),
                  menuSubItem("Importa dati",tabName = "importa"),
                  menuSubItem("Variabili",tabName = "variabili"),
                  menuSubItem("Oggetti",tabName = "oggetti"),
                  actionButton("reset","Reset",style='padding:4px; font-size:80%')
                  ),
                menuItem(text = "Statistica descrittiva",icon = shiny::icon("bar-chart"),
                         menuSubItem("Vedi dati",tabName = "vedi"),
                         menuSubItem("Summary",tabName = "summary"),
                         menuSubItem("Graf. dispersione",tabName = "graf_disp"),
                         menuSubItem("Istogramma",tabName = "graf_hist"),
                         menuSubItem("Box plot",tabName = "graf_box")
                ),
                menuItem(text = "Statistica inferenziale",icon = shiny::icon("line-chart"),
                         menuSubItem("Test media: una popolazione",tabName = "ttest1"),
                         menuSubItem("Test media: due popolazioni",tabName = "ttest2"),
                         menuSubItem("Test varianza: due popolazioni",tabName = "ftest"),
                         menuSubItem("Anova",tabName = "anovatest"),
                         menuSubItem("Outliers",tabName = "outlierstest")
                ),
                menuItem(text = "Regressione lineare",icon = shiny::icon("line-chart"),
                         menuSubItem("Semplice",tabName = "regrsemplice"),
                         menuSubItem("Polinomiale",tabName = "regrpoli"),
                         menuSubItem("Multivariata",tabName = "regrmulti")
                ),
                hr(),
                menuItem(text = "Distribuzioni",icon = shiny::icon("area-chart"),
                         menuSubItem("Normale",tabName = "normale"),
                         menuSubItem("t Student",tabName = "tstudent"),
                         menuSubItem("Chi quadro",tabName = "chiquadro"),
                         menuSubItem("F",tabName = "f")
                ),
                menuItem(text="Simulazioni",icon=shiny::icon("comments"),
                         menuSubItem("Teorema del limite centrale",tabName = "limcentr"),
                         menuSubItem("Stima della media",tabName = "intconf"),
                         menuSubItem("Test d'ipotesi",tabName = "h0"),
                         menuSubItem("Potenza di un test",tabName = "potenza"),
                         menuSubItem("Anova",tabName = "anova"),
                         menuSubItem("Regressione",tabName = "regr")
                         ),
                hr(),
                menuItem(text = "File",icon = icon("briefcase", lib = "font-awesome"),
                         # menuSubItem("Dispensa",tabName = "dispensa"),
                         # menuSubItem("Diapositive",tabName = "diapositive"),
                         tags$header(
                           em(  
                             a(href="https://dispensemodunivar.netlify.app/",  "   Dispense" ,target="_blank",style="white-space: pre-wrap")
                           )
                         ),
                         br(),
                         actionButton("quit", "Quit",onclick = "setTimeout(function(){window.close();},200);",
                                      style='padding:4px; font-size:80%')
                        )))


# Dati --------------------------------------------------------------------

body<-dashboardBody(
  tags$head(tags$link(rel = "stylesheet", type = "text/css", href = "custom.css")),  
  fluidRow(useShinyjs(),
    tabItems(
      tabItem(tabName = "esempi",
              fluidPage(titlePanel("Seleziona dati esempio"),
              column(12,
                     uiOutput('lista_esempi')),
              column(2,
                     radioButtons("esempi_hd", "Display",
                                  choices = c(Head = "head",
                                              All = "all"),
                                  selected = "head")),
              column(8,
                     div(style = 'overflow-x: scroll;',tableOutput("dati_esempio"))))),
      
      tabItem(tabName = "importa",
              fluidPage(titlePanel("Importa dati"),
                tabsetPanel(type = "tabs",
                            tabPanel("Excel",
                                     column(12,
                                       fileInput("file_xlsx", "Scegli file Excel",
                                                   multiple = FALSE,
                                                   accept = c(".xlx",".xlsx"))),
                                     column(12,
                                            checkboxInput("header", "Header", TRUE)),
                                     column(2,
                                           numericInput("foglio_n", label = "Foglio n.",value = 1,min = 1,max = 100)
                                            ),
                                     column(2,
                                            radioButtons("disp_xlx", "Display",
                                                         choices = c(Head = "head",
                                                                     All = "all"),
                                                         selected = "head")),
                                     
                                     column(8,
                                            div(style = 'overflow-x: scroll;',tableOutput("contents_xlsx")))),
                            tabPanel("CSV", 
                                     column(12,
                                            fileInput("file_csv", "Scegli file CSV",
                                                      multiple = FALSE,accept = c(".csv")
                                            )),
                                     column(12,
                                            checkboxInput("header", "Header", TRUE)),
                                     column(2,
                                            radioButtons("sep", "Separator",
                                                         choices = c(Comma = ",",
                                                                     Semicolon = ";",
                                                                     Tab = "\t"),
                                                         selected = ";"),
                                            radioButtons("quote", "Quote",
                                                         choices = c(None = "",
                                                                     "Double Quote" = '"',
                                                                     "Single Quote" = "'"),
                                                         selected = '"')),
                                     column(2,
                                            radioButtons("disp_csv", "Display",
                                                         choices = c(Head = "head",
                                                                     All = "all"),
                                                         selected = "head")),
                                     
                                     column(8,
                                            div(style = 'overflow-x: scroll;',tableOutput("contents_csv")))),
                            tabPanel("Incolla",
                                     column(12,
                                            br(),
                                            actionButton("file_incolla", label = "Incolla"),
                                            br(),
                                            br(),
                                            br(),
                                            br()),
                                     column(2,
                                            radioButtons("disp_incolla", "Display",
                                                         choices = c(Head = "head",
                                                                     All = "all"),
                                                         selected = "head")),
                                     column(8,
                                            div(style = 'overflow-x: scroll;',tableOutput("contents_incolla"))))))),
      
      tabItem(tabName = "variabili",
              fluidPage(titlePanel("Variabili"),
                        tabsetPanel(type = "tabs",
                                    tabPanel("Variabile nomi righe",
                                             column(12,
                                                uiOutput("var_nomi"),
                                                textOutput("avviso_nomi")),
                                             column(12,"Nomi righe",
                                                verbatimTextOutput("nomi_righe"))),
                                    tabPanel("Variabili qualitative",
                                             column(4,
                                                 uiOutput("var_quali")),
                                             column(8,"Variabili quantitative",
                                                verbatimTextOutput("var_quanti")))))),
      
      tabItem(tabName = "oggetti",
              fluidPage(titlePanel("Oggetti"),
                        column(4,
                               uiOutput("righe_tolte")),
                        column(8,"Righe cancellate",
                               verbatimTextOutput("righe_restanti"),
                               actionButton("desel_righe","Deseleziona tutte le righe")))), 

# Statistica descrittiva --------------------------------------------------

      tabItem(tabName = "vedi",
              fluidPage(titlePanel("Dati"),
                        div(style = 'overflow-x: scroll;',DT::dataTableOutput("dati")))),
      
      tabItem(tabName = "summary",
              fluidPage(titlePanel("Descrittori di posizione e di dispersione "),
                        uiOutput("var_gruppo"),
                        verbatimTextOutput("sum_dati"))),
      
      tabItem(tabName = "graf_disp",
              fluidPage(titlePanel("Grafico di dispersione "),
                        column(8,
                               uiOutput("graf_disp_var")),
                        column(4,
                               uiOutput("graf_disp_var_gr")),
                        column(8,
                               plotOutput("graf_disp",click = "graf_disp_click",dblclick = "graf_disp_dblclick",
                                          brush = brushOpts(id="graf_disp_brush",resetOnNew = TRUE))),
                        column(2,
                               checkboxInput("graf_disp_labels", label = "Etichette", value = FALSE)),
                        column(2,
                               uiOutput("graf_disp_gr")),
                        column(12,
                               br(),
                               actionButton("graf_disp_canc_brush","Cancella dati selezionati"),
                               actionButton("graf_disp_ripr_brush","Ripristina dati cancellati"),
                               verbatimTextOutput("graf_disp_selez")))),

      tabItem(tabName = "graf_hist",
              fluidPage(titlePanel("Istogramma"),
                        column(8,
                               uiOutput("graf_hist_var")),
                        column(4,
                               uiOutput("graf_hist_var_gr")),
                        column(8,
                               plotOutput("graf_hist")),
                        column(2),
                        column(2,
                               uiOutput("graf_hist_gr")),
                        column(3,
                               selectInput("graf_hist_tipo","",choices = c("conteggio","percentuale",
                                                                           "densità"),selected=1)),
                        column(4,
                               uiOutput("graf_hist_bin")))),

      tabItem(tabName = "graf_box",
              fluidPage(titlePanel("Box plot"),
                        column(8,
                               uiOutput("graf_box_var")),
                        column(4,
                               uiOutput("graf_box_var_gr")),
                        column(8,
                               plotOutput("graf_box",click = "graf_box_click",dblclick = "graf_box_dblclick",
                                          brush = brushOpts(id="graf_box_brush",resetOnNew = TRUE))),
                        column(2,
                               checkboxInput("graf_box_notch", label = "Notch", value = FALSE)),
                        column(2,
                               uiOutput("graf_box_gr")),
                        column(12,
                               br(),
                               actionButton("graf_box_canc_brush","Cancella dati selezionati"),
                               actionButton("graf_box_ripr_brush","Ripristina dati cancellati"),
                               verbatimTextOutput("graf_box_selez")))),

# Inferenziale -------------------------------------------------------------

tabItem(tabName = "ttest1",
        fluidPage(titlePanel("Test sulla media: una popolazione gaussiana"),
                  tabsetPanel(type = "tabs",
                              tabPanel("Test",
                                      # column(12,div("Stima della media",style="font-size:150%;")),
                                      column(4,
                                             uiOutput("ttest1_variab")),
                                      column(4,
                                              radioButtons("ttest1_var", label = "",
                                                           choices = list("Varianza nota" = 1, "Varianza non nota" = 2),
                                                           selected = 2)),
                                      column(4,
                                             uiOutput("ttest1_var_nota")),
                                      hr(),
                                      column(12,
                                              h3(textOutput("ttest1_Test1")),
                                              h3(textOutput("ttest1_Test2"))),       
                                              hr(),
                                      column(4,
                                              uiOutput("ttest1_H0"),
                                              h4("Ipotesi:"),
                                              h4(uiOutput("ttest1_H0_txt")),
                                              br(),
                                              sliderInput(inputId="ttest1_alfa",label = "Significatività",min = 0,max = 1,value = 0.05,
                                                          step=0.01),
                                              textOutput("ttest1_stat"),
                                              textOutput("ttest1_pval"),
                                              hr(),
                                              h4(textOutput("ttest1_media_camp_titolo")),
                                              textOutput("ttest1_media_camp"),
                                              textOutput("ttest1_sd_camp"),
                                              br(),
                                              h4(textOutput("ttest1_ic_titolo")),
                                              textOutput("ttest1_ic_inf"),
                                              textOutput("ttest1_ic_sup")
                                             ),
                                       column(8,
                                              plotOutput("ttest1_graf_distr"))
           
                                        ),
                              
                              tabPanel("Verifica ipotesi",
                                      column(4,h3("Test di Shapiro-Wilk")), 
                                      column(8,h3("QQ-plot")),       
                                      hr(),
                                      hr(),
                                      hr(),
                                      column(4,
                                              verbatimTextOutput("ttest1_shapiro")),
                                       column(8,
                                              plotOutput("ttest1_qqplot"))))
        )),

tabItem(tabName = "ttest2",
        fluidPage(titlePanel("Test sulla media: due popolazioni gaussiane"),
                  tabsetPanel(type = "tabs",
                              tabPanel("Test: dati accoppiati",
                                       # column(12,div("Stima della media",style="font-size:150%;")),
                                       column(4,
                                              uiOutput("ttest2a_variab1"),
                                              uiOutput("ttest2a_variab2")),
                                       column(4,
                                              radioButtons("ttest2a_var", label = "",
                                                           choices = list("Varianza differenze nota" = 1, "Varianza differenze non nota" = 2),
                                                           selected = 2)),
                                       column(4,
                                              uiOutput("ttest2a_var_nota")),
                                       hr(),
                                       column(12,
                                              h3(textOutput("ttest2a_Test1")),
                                              h3(textOutput("ttest2a_Test2"))),       
                                       hr(),
                                       column(4,
                                              uiOutput("ttest2a_H0"),
                                              h4("Ipotesi:"),
                                              h4(uiOutput("ttest2a_H0_txt")),
                                              br(),
                                              sliderInput(inputId="ttest2a_alfa",label = "Significatività",min = 0,max = 1,value = 0.05,
                                                          step=0.01),
                                              textOutput("ttest2a_stat"),
                                              textOutput("ttest2a_pval"),
                                              hr(),
                                              h4(textOutput("ttest2a_media_camp_titolo")),
                                              textOutput("ttest2a_media_camp"),
                                              textOutput("ttest2a_sd_camp"),
                                              br(),
                                              h4(textOutput("ttest2a_ic_titolo")),
                                              textOutput("ttest2a_ic_inf"),
                                              textOutput("ttest2a_ic_sup")
                                       ),
                                       column(8,
                                              plotOutput("ttest2a_graf_distr"))
                                       
                              ),
                              
                              tabPanel("Verifica ipotesi: dati accoppiati",
                                       column(4,h3("Test di Shapiro-Wilk")), 
                                       column(8,h3("QQ-plot")),       
                                       hr(),
                                       hr(),
                                       hr(),
                                       column(4,
                                              verbatimTextOutput("ttest2a_shapiro")),
                                       column(8,
                                              plotOutput("ttest2a_qqplot"))),
                              
                              
                              tabPanel("Test: dati indipendenti",
                                       # column(12,div("Stima della media",style="font-size:150%;")),
                                       column(4,
                                              uiOutput("ttest2_variab1"),
                                              uiOutput("ttest2_variab2")),
                                       column(4,
                                              radioButtons("ttest2_var", label = "",
                                                           choices = list("Varianze note" = 1, "Varianze non note" = 2),
                                                           selected = 2)),
                                       column(4,
                                              uiOutput("ttest2_var_nota1"),
                                              uiOutput("ttest2_var_nota2"),
                                              uiOutput("ttest2_var_uguale")),
                                       hr(),
                                       column(12,
                                              h3(textOutput("ttest2_Test1")),
                                              h3(textOutput("ttest2_Test2"))),       
                                       hr(),
                                       column(4,
                                              uiOutput("ttest2_H0"),
                                              h4("Ipotesi:"),
                                              h4(uiOutput("ttest2_H0_txt")),
                                              br(),
                                              sliderInput(inputId="ttest2_alfa",label = "Significatività",min = 0,max = 1,value = 0.05,
                                                          step=0.01),
                                              textOutput("ttest2_stat"),
                                              textOutput("ttest2_pval"),
                                              hr(),
                                              h4(textOutput("ttest2_media_camp_titolo")),
                                              textOutput("ttest2_media_camp1"),
                                              textOutput("ttest2_sd_camp1"),
                                              br(),
                                              textOutput("ttest2_media_camp2"),
                                              textOutput("ttest2_sd_camp2"),
                                              br(),
                                              textOutput("ttest2_ds_c"),
                                              br(),
                                              h4(textOutput("ttest2_ic_titolo")),
                                              textOutput("ttest2_ic_inf"),
                                              textOutput("ttest2_ic_sup")
                                       ),
                                       column(8,
                                              div(textOutput("ttest2_errore"),style="font-size: 175%;color: red;font-weight: bold;"),
                                              plotOutput("ttest2_graf_distr"))
                              ),
                              
                              tabPanel("Verifica ipotesi: dati indipendenti",
                                       column(4,h3("Test di Shapiro-Wilk")), 
                                       column(8,h3("QQ-plot")),       
                                       hr(),
                                       hr(),
                                       hr(),
                                       column(4,
                                              verbatimTextOutput("ttest2_shapiro1")),
                                       column(8,
                                              plotOutput("ttest2_qqplot1")),
                                       column(12,
                                              hr()),
                                       column(4,
                                              verbatimTextOutput("ttest2_shapiro2")),
                                       column(8,
                                              plotOutput("ttest2_qqplot2")))
                              )
        )),

tabItem(tabName = "ftest",
        fluidPage(titlePanel("Test sulla varianza: due popolazioni gaussiane"),
                  tabsetPanel(type = "tabs",
                              tabPanel("Test",
                                       column(4,
                                              uiOutput("ftest_variab1"),
                                              uiOutput("ftest_variab2")),
                                       hr(),
                                       column(12,
                                              h3("F-test")),       
                                       hr(),
                                       column(4,
                                              h4("Ipotesi:"),
                                              h4(uiOutput("ftest_H0_txt")),
                                              br(),
                                              sliderInput(inputId="ftest_alfa",label = "Significatività",min = 0,max = 1,value = 0.05,
                                                          step=0.01),
                                              textOutput("ftest_stat"),
                                              textOutput("ftest_pval"),
                                              hr(),
                                              h4(textOutput("ftest_media_camp_titolo")),
                                              textOutput("ftest_sd_camp1"),
                                              textOutput("ftest_sd_camp2"),
                                              br(),
                                              h4(textOutput("ftest_ic_titolo")),
                                              textOutput("ftest_ic_inf"),
                                              textOutput("ftest_ic_sup")
                                       ),
                                       column(8,
                                              div(textOutput("ftest_errore"),style="font-size: 175%;color: red;font-weight: bold;"),
                                              plotOutput("ftest_graf_distr"))
                                       
                              ),
                              
                              tabPanel("Verifica ipotesi",
                                       column(4,h3("Test di Shapiro-Wilk")), 
                                       column(8,h3("QQ-plot")),       
                                       hr(),
                                       hr(),
                                       hr(),
                                       column(4,
                                              verbatimTextOutput("ftest_shapiro1")),
                                       column(8,
                                              plotOutput("ftest_qqplot1")),
                                       column(12,
                                              hr()),
                                       column(4,
                                              verbatimTextOutput("ftest_shapiro2")),
                                       column(8,
                                              plotOutput("ftest_qqplot2"))
                              )
                  )
        )),

tabItem(tabName = "anovatest",
        fluidPage(titlePanel("Analisi della varianza"),
                  tabsetPanel(type = "tabs",
                              tabPanel("Anova: un fattore",
                                       column(4,
                                              uiOutput("anovatest_variab1"),
                                              uiOutput("anovatest_variab2")),
                                       hr(),
                                       column(12,
                                              h3("Anova a una via")),       
                                       hr(),
                                       column(4,
                                              h4("Ipotesi:"),
                                              h4(HTML("H<SUB>0</SUB>: &alpha;<SUB>1</SUB> = &alpha;<SUB>2</SUB> = ... = &alpha;<SUB>a</SUB> = 0 <br>
                                                       H<SUB>1</SUB>: &alpha;<SUB>i</SUB>  &ne; 0 per almeno un i")),
                                              br(),
                                              sliderInput(inputId="anovatest_alfa",label = "Significatività",min = 0,max = 1,value = 0.05,
                                                          step=0.01),
                                              textOutput("anovatest_stat"),
                                              textOutput("anovatest_pval")
                                       ),
                                       column(8,
                                              plotOutput("anovatest_graf_distr")),
                                       column(12,
                                              hr(),
                                              h4("R output"),
                                              verbatimTextOutput("anovatest_R"))
                                       
                              ),
                              
                              tabPanel("Verifica ipotesi: 1-waov", 
                                       column(12,h3("Normalità dei residui")),
                                       column(4,h4("Test di Shapiro-Wilk")), 
                                       column(8,h4("QQ-plot")),       
                                       hr(),
                                       hr(),
                                       hr(),
                                       column(4,
                                              verbatimTextOutput("anovatest_shapiro1")),
                                       column(8,
                                              plotOutput("anovatest_qqplot1")),
                                       column(12,
                                              br(),
                                              h3("Omoschedasticità")),
                                       column(7,
                                              h4("Test di Bartlett"),
                                              h5("(poco robusto (sensibile ipotesi normalità))"),
                                              verbatimTextOutput("anovatest_bartlett")
                                              ),
                                       column(7,
                                              h4("Test di Fligner-Killeen"),
                                              h5("(più robusto)"),
                                              verbatimTextOutput("anovatest_fligner")
                                              ),
                                       column(7,
                                              h4("Test di Levene "),
                                              h5("(da usare se diverse numerosità campionarie)"),
                                              verbatimTextOutput("anovatest_levene")),
                                       column(7,
                                              h4("Test di Breusch-Pagan"),
                                              h5("(adatto a grandi campioni)"),
                                              verbatimTextOutput("anovatest_bp")),
                                       column(7,
                                              h4("Test di Cochran"),
                                              h5("(test della varianza massima (minima))"),
                                              verbatimTextOutput("anovatest_cochran"))
                                       ),
                              

                              tabPanel("Anova: due fattori",
                                       column(4,
                                              uiOutput("anova2test_variab1")),
                                       column(12),
                                       column(4,
                                              uiOutput("anova2test_variab2")),
                                       column(4,
                                              uiOutput("anova2test_variab3")),
                                       column(12),
                                       hr(),
                                       column(4,
                                              h3("Anova a due vie")), 
                                       column(4),
                                       column(4,
                                              sliderInput(inputId="anova2test_alfa",label = "Significatività",min = 0,max = 1,value = 0.05,
                                                          step=0.01)),
                                       column(4,
                                              h4("Ipotesi 1:"),
                                              h4(HTML("H<SUB>0,1</SUB>: &alpha;<SUB>1</SUB> = &alpha;<SUB>2</SUB> = ... =&alpha;<SUB>a</SUB> = 0 <br>
                                                      H<SUB>1,1</SUB>: &alpha;<SUB>i</SUB> &ne; 0 per almeno un i")),
                                              br(),
                                              textOutput("anova2test_stat1"),
                                              textOutput("anova2test_pval1")
                                              ),
                                       column(8,
                                              plotOutput("anova2test_graf_distr1")),
                                       column(12,br()),
                                       column(4,
                                              h4("Ipotesi 2:"),
                                              h4(HTML("H<SUB>0,2</SUB>: &beta;<SUB>1</SUB> = &beta;<SUB>2</SUB> = ... =&beta;<SUB>b</SUB> = 0 <br>
                                                      H<SUB>1,2</SUB>: &beta;<SUB>j</SUB> &ne; 0 per almeno un j")),
                                              br(),
                                              textOutput("anova2test_stat2"),
                                              textOutput("anova2test_pval2")
                                              ),
                                       column(8,
                                              plotOutput("anova2test_graf_distr2")),
                                       column(12,br()),
                                       column(4,
                                              uiOutput("anova2test_h12_ipotesi"),
                                              br(),
                                              textOutput("anova2test_stat12"),
                                              textOutput("anova2test_pval12")
                                              ),
                                       column(8,
                                              plotOutput("anova2test_graf_distr12")),
                                       column(12,
                                              hr(),
                                              h4("R output"),
                                              verbatimTextOutput("anova2test_R")),
                                       column(12,
                                              hr(),
                                              h4("Grafici interazione")),
                                       column(6,
                                              plotOutput("anova2test_graf_interaz1")),
                                       column(6,
                                              plotOutput("anova2test_graf_interaz2"))
                                       
                                      ),
                              tabPanel("Verifica ipotesi: 2-waov", 
                                       column(12,h3("Normalità dei residui")),
                                       column(4,h4("Test di Shapiro-Wilk")), 
                                       column(8,h4("QQ-plot")),       
                                       hr(),
                                       hr(),
                                       hr(),
                                       column(4,
                                              verbatimTextOutput("anova2test_shapiro1")),
                                       column(8,
                                              plotOutput("anova2test_qqplot1")),
                                       column(12,
                                              br(),
                                              h3("Omoschedasticità")),
                                       column(7,
                                              h4("Test di Bartlett"),
                                              h5("(poco robusto (sensibile ipotesi normalità))"),
                                              verbatimTextOutput("anova2test_bartlett")),
                                       column(7,
                                              h4("Test di Fligner-Killeen"),
                                              h5("(più robusto)"),
                                              verbatimTextOutput("anova2test_fligner")),
                                       column(7,
                                              h4("Test di Levene "),
                                              h5("(da usare se diverse numerosità campionarie)"),
                                              verbatimTextOutput("anova2test_levene")),
                                       column(7,
                                              h4("Test di Breusch-Pagan"),
                                              h5("(adatto a grandi campioni)"),
                                              verbatimTextOutput("anova2test_bp")),
                                       column(7,
                                              h4("Test di Cochran"),
                                              h5("(test della varianza massima (minima))"),
                                              verbatimTextOutput("anova2test_cochran"))
                                       ),
                                       
                              tabPanel("Anova: tre fattori",
                                       column(4,
                                              uiOutput("anova3test_variab1")),
                                       column(12),
                                       column(4,
                                              uiOutput("anova3test_variab2")),
                                       column(4,
                                              uiOutput("anova3test_variab3")),
                                       column(4,
                                              uiOutput("anova3test_variab4")),
                                       column(12),
                                       hr(),
                                       column(4,
                                              h3("Anova a tre vie")), 
                                       column(12,
                                              h4("R output"),
                                              verbatimTextOutput("anova3test_R")),
                                       column(12,
                                              hr(),
                                              h4("Grafici interazione")),
                                       column(6,
                                              h6(textOutput("anova3test_graf_interaz_txt"))),
                                       column(12,
                                              plotOutput("anova3test_graf_interaz1")),
                                       column(12,br()),
                                       column(12,
                                              plotOutput("anova3test_graf_interaz2")))
                             
                              
                              ))),

tabItem(tabName = "outlierstest",
        fluidPage(titlePanel("Test per la determinazione di outliers"),
                  column(4,
                         uiOutput("outlierstest_variab")),
                  column(12),
                  column(6,
                         h4("Test di Dixon"),
                         h5("(differenza dalla media maggiore)"),
                         verbatimTextOutput("outlierstest_dixon_magg")),
                  column(6,
                         h4("Test di Dixon"),
                         h5("(differenza dalla media minore)"),
                         verbatimTextOutput("outlierstest_dixon_min")),
                  column(12),
                  column(6,
                         h4("Test di Grubbs"),
                         h5("(differenza dalla media maggiore)"),
                         verbatimTextOutput("outlierstest_grubbs_magg")),
                  column(6,
                         h4("Test di Grubbs"),
                         h5("(differenza dalla media minore)"),
                         verbatimTextOutput("outlierstest_grubbs_min"))
                  )),

# Regressione -----------------------------------------------------------

tabItem(tabName = "regrsemplice",
        fluidPage(titlePanel("Regressione lineare semplice"),
                  tabsetPanel(type = "tabs",
                              tabPanel("Regressione",
                                       column(4,
                                         uiOutput("regrsemplice_variaby")),
                                       column(4,
                                        uiOutput("regrsemplice_variabx")),
                                       column(12),
                                       column(4,
                                              h3("Parametri regressione"),
                                              h4("Stima puntuale"),
                                              verbatimTextOutput("regrsemplice_parpt"),
                                              h4("Stima per intervallo"),
                                              verbatimTextOutput("regrsemplice_parint"),
                                              hr(),
                                              h3("Previsione"),
                                              numericInput(inputId = "regrsemplice_prevx",label = "Punto previsione (x)",width = "65%",value = ""),
                                              verbatimTextOutput("regrsemplice_prev"),
                                              h3("Previsione inversa"),
                                              numericInput(inputId = "regrsemplice_prevy",label = "Punto previsione inversa (y)",width = "65%",value = ""),
                                              verbatimTextOutput("regrsemplice_prev_inv")),
                                       column(8,
                                             plotOutput("regrsemplice_graf"),
                                             br(),
                                             h3("R output"),
                                             verbatimTextOutput("regrsemplice_summary"))
                              ),
                  
                              tabPanel("Verifica ipotesi",
                                       column(4,h3("Media dei residui nulla")),
                                       column(8,h3("Linearità")),
                                       column(4,h4("t-test"),
                                              verbatimTextOutput("regrsemplice_verifhp_ttest")), 
                                       column(8,h4("Residui vs. fitted"),
                                              plotOutput("regrsemplice_verifhp_grlin")),
                                       column(12,hr()),
                                       column(12,h3("Normalità dei residui")),
                                       column(4,h4("Test di Shapiro-Wilk"),
                                              verbatimTextOutput("regrsemplice_verifhp_shapiro")),
                                       column(8,h4("QQ-plot"),
                                              plotOutput("regrsemplice_verifhp_qqplot")),
                                       column(12,hr()),
                                       column(12,h3("Omoschedasticità dei residui")),
                                       column(4,h4("Test di Breusch-Pagan"),
                                              verbatimTextOutput("regrsemplice_verifhp_bp")),
                                       column(8,h4(HTML("&radic;residui vs. fitted")),
                                              plotOutput("regrsemplice_verifhp_omosch")),
                                       column(12,hr()),
                                       column(12,h3("Correlazione seriale dei residui")),
                                       column(4,h4("Test di Durbin-Watson"),
                                              verbatimTextOutput("regrsemplice_verifhp_dw")),
                                       column(8,h4("res(n) vs. res(n-1)"),
                                              plotOutput("regrsemplice_verifhp_corr"))
                              )))),

tabItem(tabName = "regrpoli",
        fluidPage(titlePanel("Regressione polinomiale"),
                  tabsetPanel(type = "tabs",
                              tabPanel("Regressione",
                                       column(4,
                                              uiOutput("regrpoli_variaby")),
                                       column(4,
                                              uiOutput("regrpoli_variabx")),
                                       column(2),
                                       column(2,
                                              numericInput("regrpoli_grado",label="grado del polinomio",width = "40%",value = 2)),
                                       column(12),
                                       column(4,
                                              h3("Parametri regressione"),
                                              h4("Stima puntuale"),
                                              verbatimTextOutput("regrpoli_parpt"),
                                              h4("Stima per intervallo"),
                                              verbatimTextOutput("regrpoli_parint"),
                                              hr(),
                                              h3("Previsione"),
                                              numericInput(inputId = "regrpoli_prevx",label = "Punto previsione",width = "30%",value = ""),
                                              verbatimTextOutput("regrpoli_prev")),
                                       column(8,
                                              plotOutput("regrpoli_graf"),
                                              br(),
                                              h3("R output"),
                                              verbatimTextOutput("regrpoli_summary"))
                              ),
                              
                              tabPanel("Verifica ipotesi",
                                       column(4,h3("Media dei residui nulla")),
                                       column(8,h3("Linearità")),
                                       column(4,h4("t-test"),
                                              verbatimTextOutput("regrpoli_verifhp_ttest")), 
                                       column(8,h4("Residui vs. fitted"),
                                              plotOutput("regrpoli_verifhp_grlin")),
                                       column(12,hr()),
                                       column(12,h3("Normalità dei residui")),
                                       column(4,h4("Test di Shapiro-Wilk"),
                                              verbatimTextOutput("regrpoli_verifhp_shapiro")),
                                       column(8,h4("QQ-plot"),
                                              plotOutput("regrpoli_verifhp_qqplot")),
                                       column(12,hr()),
                                       column(12,h3("Omoschedasticità dei residui")),
                                       column(4,h4("Test di Breusch-Pagan"),
                                              verbatimTextOutput("regrpoli_verifhp_bp")),
                                       column(8,h4(HTML("&radic;residui vs. fitted")),
                                              plotOutput("regrpoli_verifhp_omosch")),
                                       column(12,hr()),
                                       column(12,h3("Correlazione seriale dei residui")),
                                       column(4,h4("Test di Durbin-Watson"),
                                              verbatimTextOutput("regrpoli_verifhp_dw")),
                                       column(8,h4("res(n) vs. res(n-1)"),
                                              plotOutput("regrpoli_verifhp_corr"))
                                       
                              )))),

tabItem(tabName = "regrmulti",
        fluidPage(titlePanel("Regressione multivariata"),
                  tabsetPanel(type = "tabs",
                              tabPanel("Regressione",
                                       column(4,
                                              uiOutput("regrmulti_variaby")),
                                       column(4,
                                              uiOutput("regrmulti_variabx")),
                                       column(2),
                                       column(2,
                                              radioButtons("regrmulti_addi", label = h4("Modello:"),
                                                           choices = list("additivo" = 1, "interattivo" = 2), 
                                                           selected = 1),
                                              checkboxInput("regrmulti_intercetta",
                                                label = "Intercetta", 
                                                value = TRUE)),
                                       column(12),
                                       column(4,
                                              h3("Parametri regressione"),
                                              h4("Stima puntuale"),
                                              verbatimTextOutput("regrmulti_parpt"),
                                              h4("Stima per intervallo"),
                                              verbatimTextOutput("regrmulti_parint"),
                                              hr(),
                                              h3("Previsione"),
                                              textInput(inputId = "regrmulti_prevx",label = "Punto previsione (coord. separate da spazio)",value = ""),
                                              verbatimTextOutput("regrmulti_prev")),
                                       column(8,
                                              plotOutput("regrmulti_graf"),
                                              br(),
                                              h3("R output"),
                                              verbatimTextOutput("regrmulti_summary"))
                              ),
                              
                              tabPanel("Verifica ipotesi",
                                       column(4,h3("Media dei residui nulla")),
                                       column(8,h3("Linearità")),
                                       column(4,h4("t-test"),
                                              verbatimTextOutput("regrmulti_verifhp_ttest")), 
                                       column(8,h4("Residui vs. fitted"),
                                              plotOutput("regrmulti_verifhp_grlin")),
                                       column(12,hr()),
                                       column(12,h3("Normalità dei residui")),
                                       column(4,h4("Test di Shapiro-Wilk"),
                                              verbatimTextOutput("regrmulti_verifhp_shapiro")),
                                       column(8,h4("QQ-plot"),
                                              plotOutput("regrmulti_verifhp_qqplot")),
                                       column(12,hr()),
                                       column(12,h3("Omoschedasticità dei residui")),
                                       column(4,h4("Test di Breusch-Pagan"),
                                              verbatimTextOutput("regrmulti_verifhp_bp")),
                                       column(8,h4(HTML("&radic;residui vs. fitted")),
                                              plotOutput("regrmulti_verifhp_omosch")),
                                       column(12,hr()),
                                       column(12,h3("Correlazione seriale dei residui")),
                                       column(4,h4("Test di Durbin-Watson"),
                                              verbatimTextOutput("regrmulti_verifhp_dw")),
                                       column(8,h4("res(n) vs. res(n-1)"),
                                              plotOutput("regrmulti_verifhp_corr"))
                              )))),

# Distribuzioni -----------------------------------------------------------

    tabItem(tabName = "normale",
            fluidPage(titlePanel("Distribuzione normale"),
                      column(8,
                             plotOutput("graf_normale")),
                      column(4,
                             sliderInput(inputId="graf_norm_media",label = "Media",min = -10,max = 10,value = 0,
                                          step=1)),
                      column(4,
                             sliderInput(inputId="graf_norm_ds",label = "Deviazione standard",min = 0.1,max = 5,
                                         value = 1, step=0.1)),
                      hr(),
                      hr(),
                      hr(),
                      hr(),
                      hr(),
                      hr(),
                      hr(),
                      hr(),
                      hr(),
                      hr(),
                      hr(),
                      hr(),
                      hr(),
                      hr(),
                      hr(),
                      column(4,
                             #textOutput("txt"),
                             div(textOutput("norm_txt"),style="font-size:125%;"),
                             verbatimTextOutput("norm_testo")),
                      hr(),
                      hr(),
                      hr(),
                      hr(),
                      hr(),
                      column(4,
                             selectInput(inputId = "graf_norm_area",
                                         label = "Area:",
                                         choices = c(" "="nessuna",
                                                     "Coda inferiore"="lower", 
                                                     "Coda superiore"="upper", 
                                                     "Due code"="both",
                                                     "Mezzo"="middle"),
                                         selected = "nessuna")),
                      column(4,
                             uiOutput("graf_norm_a")),
                      column(4,
                             uiOutput("graf_norm_b")),
                      hr(),
                      hr(),
                      hr(),
                      hr(),
                      hr(),
                      column(4,
                             uiOutput("graf_norm_camp")),
                      column(4,
                             uiOutput("graf_norm_camp_num"))
                      
            )),

tabItem(tabName = "tstudent",
        fluidPage(titlePanel("Distribuzione t di Student"),
                  column(8,
                         plotOutput("graf_tstudent")),
                  column(4,
                         sliderInput(inputId="graf_tstudent_dof",label = "Gradi di libertà",min = 1,max = 1000,value = 1,
                                     step=1)),
                  hr(),
                  hr(),
                  hr(),
                  hr(),
                  hr(),
                  hr(),
                  hr(),
                  hr(),
                  hr(),
                  hr(),
                  hr(),
                  hr(),
                  hr(),
                  hr(),
                  hr(),
                  column(4,
                         #textOutput("txt"),
                         div(textOutput("tstudent_txt"),style="font-size:125%;"),
                         verbatimTextOutput("tstudent_testo")),
                  hr(),
                  hr(),
                  hr(),
                  hr(),
                  hr(),
                  column(4,
                         selectInput(inputId = "graf_tstudent_area",
                                     label = "Area:",
                                     choices = c(" "="nessuna",
                                                 "Coda inferiore"="lower", 
                                                 "Coda superiore"="upper", 
                                                 "Due code"="both",
                                                 "Mezzo"="middle"),
                                     selected = "nessuna")),
                  column(4,
                         uiOutput("graf_tstudent_a")),
                  column(4,
                         uiOutput("graf_tstudent_b")),
                  hr(),
                  hr(),
                  hr(),
                  hr(),
                  hr(),
                  column(4,
                         uiOutput("graf_tstudent_camp")),
                  column(4,
                         uiOutput("graf_tstudent_camp_num"))
                  


        )),

tabItem(tabName = "chiquadro",
        fluidPage(titlePanel("Distribuzione chi qaudro"),
                  
                  column(8,
                         plotOutput("graf_chi")),
                  column(4,
                         sliderInput(inputId="graf_chi_dof",label = "Gradi di libertà",min = 1,max = 30,value = 1,
                                     step=1)),
                  hr(),
                  hr(),
                  hr(),
                  hr(),
                  hr(),
                  hr(),
                  hr(),
                  hr(),
                  hr(),
                  hr(),
                  hr(),
                  hr(),
                  hr(),
                  hr(),
                  hr(),
                  column(4,
                         #textOutput("txt"),
                         div(uiOutput("chi_txt"),style="font-size:125%;"),
                         verbatimTextOutput("chi_testo")),
                  hr(),
                  hr(),
                  hr(),
                  hr(),
                  hr(),
                  column(4,
                         selectInput(inputId = "graf_chi_area",
                                     label = "Area:",
                                     choices = c(" "="nessuna",
                                                 "Coda inferiore"="lower", 
                                                 "Coda superiore"="upper", 
                                                 "Due code"="both",
                                                 "Mezzo"="middle"),
                                     selected = "nessuna")),
                  column(4,
                         uiOutput("graf_chi_a")),
                  column(4,
                         uiOutput("graf_chi_b")),
                  hr(),
                  hr(),
                  hr(),
                  hr(),
                  hr(),
                  column(4,
                         uiOutput("graf_chi_camp")),
                  column(4,
                         uiOutput("graf_chi_camp_num"))
                  )),

tabItem(tabName = "f",
        fluidPage(titlePanel("Distribuzione F"),
                  column(8,
                         plotOutput("graf_f")),
                  column(4,
                         sliderInput(inputId="graf_f_dof1",label = "Gradi di libertà 1",min = 1,max = 30,value = 1,
                                     step=1),
                         sliderInput(inputId="graf_f_dof2",label = "Gradi di libertà 2",min = 1,max = 30,value = 1,
                                     step=1)
                  ),
                  hr(),
                  hr(),
                  hr(),
                  hr(),
                  hr(),
                  hr(),
                  hr(),
                  hr(),
                  hr(),
                  hr(),
                  hr(),
                  hr(),
                  hr(),
                  hr(),
                  hr(),
                  column(4,
                         #textOutput("txt"),
                         div(uiOutput("f_txt"),style="font-size:125%;"),
                         verbatimTextOutput("f_testo")),
                  hr(),
                  hr(),
                  hr(),
                  hr(),
                  hr(),
                  column(4,
                         selectInput(inputId = "graf_f_area",
                                     label = "Area:",
                                     choices = c(" "="nessuna",
                                                 "Coda inferiore"="lower", 
                                                 "Coda superiore"="upper", 
                                                 "Due code"="both",
                                                 "Mezzo"="middle"),
                                     selected = "nessuna")),
                  column(4,
                         uiOutput("graf_f_a")),
                  column(4,
                         uiOutput("graf_f_b")),
                  hr(),
                  hr(),
                  hr(),
                  hr(),
                  hr(),
                  column(4,
                         uiOutput("graf_f_camp")),
                  column(4,
                         uiOutput("graf_f_camp_num"))
                  )),


# Simulazioni -------------------------------------------------------------

tabItem(tabName = "limcentr",
        fluidPage(titlePanel("Teorema del limite centrale"),
                  hr(),
                  column(8,div("distribuzione della popolazione: Bernoulli",style="font-size:125%;"),
                         br(),
                         plotOutput("graf_lc_pop")),
                  column(4,
                         sliderInput(inputId="graf_lc_prob",label = "Probabilità",min = 0,max = 1,
                                     value = 0.5,step=0.1)),
                  column(4,
                         textOutput("lc_pop_media")),
                  column(4,
                         textOutput("lc_pop_var")),
                  hr(),
                  column(8,div(textOutput("graf_lc_titolo"),style="font-size:125%;"),
                         br(),
                         plotOutput("graf_lc")),
                  
                  column(4,
                         sliderInput(inputId="graf_lc_numta_camp",label = "Numerosità del campione",
                                     min = 1,max = 500,
                                     value = 1,step=1)),
                  column(4,
                         sliderInput(inputId="graf_lc_num_camp",label = "Numero campioni",
                                     min = 1,max = 10000,
                                     value = 1,step=10))
        )),

tabItem(tabName = "intconf",
        fluidPage(titlePanel("Stima della media"),
                  column(12,div("distribuzione della popolazione: Normale",style="font-size:150%;")),
                  hr(),
                  column(2,
                         numericInput("int_conf_media",label = "Media",value=0)),
                  column(2,
                         numericInput("int_conf_ds",label = "Dev. st",value=1)),
                  column(4,
                         numericInput("int_conf_numta_camp",label = "Numerosità del campione",value=10,width = "60%")),
                  column(12),
                  column(4,
                         radioButtons("int_conf_var", label = "",
                                      choices = list("Varianza nota" = 1, "Varianza non nota" = 2),
                                      selected = 1)),
                 column(12),
                  column(4,
                         div("Stima della media puntuale",style="font-size:150%;"),
                         textOutput("int_conf_media_camp"),
                         textOutput("int_conf_sd_camp"),
                         br(),
                         textOutput("int_conf_stat"),
                         hr(),
                         sliderInput(inputId="int_conf_alfa",label = "Significatività",min = 0,max = 1,value = 0,
                                     step=0.01),
                         hr(),
                         div(textOutput("int_conf_IC_txt"),style="font-size:150%;"),
                
                         textOutput("int_conf_ic_inf"),
                         textOutput("int_conf_ic_sup"),
                         hr(),
                         actionButton("resample","Ricampiona",style='padding:4px; font-size:100%')
                         
                         ),
                  column(8,
                         plotOutput("int_conf_graf_distr")),
                  column(4),
      
                  column(8,
                         hr(),
                         plotOutput("int_conf_graf_ic"))
         )),

tabItem(tabName = "h0",
        fluidPage(titlePanel("Test d'ipotesi"),
                  column(12,div("distribuzione della popolazione: Normale",style="font-size:150%;")),
                  hr(),
                  column(2,
                         numericInput("h0_media",label = "Media",value=0)),
                  column(2,
                         numericInput("h0_ds",label = "Dev. st.",value=1)),
                  column(4,
                         numericInput("h0_numta_camp",label = "Numerosità del campione",value=10,width = "60%")),                  
                  column(12),
                  column(4,
                         radioButtons("h0_var", label = "",
                                      choices = list("Varianza nota" = 1, "Varianza non nota" = 2),
                                      selected = 2)),
                  hr(),
                  column(12,
                         h3(textOutput("h0_Test1")),
                         h3(textOutput("h0_Test2"))), 
                  hr(),
                  column(4,
                         uiOutput("h0_H0"),
                         h4("Ipotesi:"),
                         h4(uiOutput("h0_H0_txt")),
                         br(),
                         sliderInput(inputId="h0_alfa",label = "Significatività",min = 0,max = 1,value = 0.05,
                                     step=0.01),
                         textOutput("h0_stat"),
                         textOutput("h0_pval"),
                         hr(),
                         br(),
                         h4(textOutput("h0_potenza_txt")),
                         uiOutput("h0_beta")
                  ),
                  column(8,
                         plotOutput("h0_graf_distr")),
                  column(4,
                         br(),
                         actionButton("h0_resample","Ricampiona",style='padding:4px; font-size:100%'),
                         checkboxInput("h0_graf_pvalue", label = "p-value", value = FALSE))
        )),
                  
tabItem(tabName = "potenza",
        fluidPage(titlePanel("Potenza di un test"),
                  column(4,
                         radioButtons("potenza_test", label = "",
                                      choices = list("z-test" = 1, "t-test" = 2),
                                      selected = 1)),
                  column(12,br()),
                  column(4,      
                         sliderInput(inputId="potenza_alfa",label = "Significatività",min = 0,max = 1,value = 0.05,
                                     step=0.01),
                         sliderInput(inputId="potenza_delta",label = "Differenza dalla media vera",min = 0,max = 10,value = 0,
                                     step=0.1),
                         sliderInput(inputId="potenza_ds",label = "Dev. st",min = 0.1,max = 5,value = 1,
                                     step=0.1),
                         sliderInput(inputId="potenza_num_pop",label = "Numerosità popolazione",min = 2,max = 100,value = 5,
                                     step=1),
                         hr(),
                         h4(textOutput("potenza_err2")),
                         uiOutput("potenza_beta"),
                         h3(" "),
                         h4(textOutput("potenza_pot_txt")),
                         uiOutput("potenza_pot")),
                  column(8,
                         plotOutput("potenza_graf_distr"))
                  
        )), 

tabItem(tabName = "anova",
        fluidPage(titlePanel("Analisi della varianza"),
                  column(12,div("distribuzione delle popolazioni: Normale",style="font-size:150%;")),
                  hr(),
                  column(2,
                         numericInput("anova_media1",label = "Media gruppo 1",value=-2)),
                  column(2,
                         numericInput("anova_media2",label = "Media gruppo 2",value=0)),
                  column(2,
                         numericInput("anova_media3",label = "Media gruppo 3",value=2)),
                  column(6),
                  column(2,
                         numericInput("anova_ds",label = "Dev. st",value=1)),
                  column(12,
                         plotOutput("anova_graf_distr")),
                  column(12,
                         br()),

                  column(2,
                         numericInput("anova_numta_camp",label = "Numerosità del campione",value=10,width = "100%")),
                  column(2,
                         actionButton("anova_resample","Ricampiona",style='padding:4px; font-size:100%')),
                 column(12),
                 column(4,
                        h4("Varianza nei gruppi"),
                        plotOutput("anova_graf_var_in"),
                        br(),
                        uiOutput("anova_graf_var_in_txt_ss")),
                 column(4,
                        h4("Varianza tra gruppi"),
                        plotOutput("anova_graf_var_tra"),
                        br(),
                        uiOutput("anova_graf_var_tra_txt_ss")),
                 column(4,
                        h4("Varianza totale"),
                        plotOutput("anova_graf_var_tot"),
                        br(),
                        uiOutput("anova_graf_var_tot_txt_ss")
                        ),
                 column(12,
                        hr()),
                 column(4,
                        h4("Ipotesi:"),
                        h4(HTML("H<SUB>0</SUB>: &mu;<SUB>1</SUB> = &mu;<SUB>2</SUB> =&mu;<SUB>3</SUB> <br>
                                H<SUB>1</SUB>: &mu;<SUB>i</SUB> &ne;&mu;<SUB>j</SUB> per almeno (i,j)")),
                        br(),
                        sliderInput(inputId="anova_alfa",label = "Significatività",min = 0,max = 1,value = 0.05,
                                    step=0.01),
                        textOutput("anova_stat"),
                        textOutput("anova_pval")),
                 column(8,
                        plotOutput("anova_graf_distr_test")),
                 column(4),
                 column(4,
                        br(),
                        checkboxInput("anova_graf_pvalue", label = "p-value", value = FALSE)),
                 column(12,
                        hr(),
                        h4("R output"),
                        verbatimTextOutput("anova_R"))
        )),

tabItem(tabName = "regr",
        fluidPage(titlePanel("Regressione lineare semplice"),
                  tabsetPanel(type="tabs",
                              tabPanel("Minimi quadrati",
                                       column(12,div(textOutput("regr_mq_titolo"),style="font-size:150%;")),
                                       hr(),
                                       column(2,
                                              numericInput("regr_mq_a",label = "Intercetta",value=0)),
                                       column(2,
                                              numericInput("regr_mq_b",label = "Pendenza",value=1)),
                                       column(2,
                                              numericInput("regr_mq_var",label = "Dev. st. errore",value=1)),
                                       column(12,br()),
                                       column(4,
                                              textInput("regr_mq_dis","Disegno sperimentale (punti sperimentali separati da spazio)", "2 4 6 8 10"),
                                              br(),
                                              h5("Matrice sperimentale"),
                                              tableOutput("regr_mq_matrexp"),
                                              actionButton("regr_mq_resample","Ricampiona",style='padding:4px; font-size:100%')),
                                       column(8,
                                              hr(),
                                              plotOutput("regr_mq_graf")),
                                       column(12,
                                              h4("stima dei parametri")),
                                       column(4,
                                              sliderInput(inputId="regr_mq_aman",label = "Intercetta",min = -30,max = 30,value = 0,
                                                          step=0.01),
                                              sliderInput(inputId="regr_mq_bman",label = "Pendenza",min = -10,max = 10,value = 0,
                                                          step=0.01)),
                                       column(2,
                                              checkboxGroupInput("regr_mq_dq",label=" ",
                                                                 choices = list("distanza" = 1, "quadrati" = 2),
                                                                 selected = 0)),
                                       column(2,
                                              br(),
                                              textOutput("regr_mq_numss"),
                                              br(),
                                              plotOutput("regr_mq_grss",height = 50)
                                       ),
                                       
                                       column(2),
                                       column(2,
                                              checkboxInput("regr_mq_rstim", label = "retta da stimare", value = TRUE),
                                              checkboxInput("regr_mq_rregr", label = "retta di regressione", value = FALSE),
                                              textOutput("regr_mq_rregr_interc"),
                                              textOutput("regr_mq_rregr_pdz")
                                       )),
     
                                       tabPanel("Significatività coefficienti",
                                                column(12,div(textOutput("regr_sp_titolo"),style="font-size:150%;")),
                                                hr(),
                                                column(2,
                                                       numericInput("regr_sp_a",label = "Intercetta",value=0)),
                                                column(2,
                                                       numericInput("regr_sp_b",label = "Pendenza",value=1)),
                                                column(2,
                                                       numericInput("regr_sp_var",label = "Dev. st. errore",value=1)),
                                                column(12,br()),
                                                column(4,
                                                       textInput("regr_sp_dis","Disegno sperimentale (punti sperimentali separati da spazio)", "2 4 6 8 10"),
                                                       br(),
                                                       h5("Matrice sperimentale"),
                                                       tableOutput("regr_sp_matrexp"),
                                                       actionButton("regr_sp_resample","Ricampiona",style='padding:4px; font-size:100%')),
                                                column(8,
                                                       hr(),
                                                       plotOutput("regr_sp_graf")),
                                                column(12,
                                                       h3("test sui parametri")),
                                                column(4,
                                                       sliderInput(inputId="regr_sp_alfa",label = "Significatività",min = 0,max = 1,value = 0.05,
                                                                   step=0.01)),
                                                column(2),
                                                column(2,
                                                       checkboxInput("regr_sp_rstim", label = "retta da stimare", value = TRUE)),
                                                
                                                column(2,
                                                       checkboxInput("regr_sp_rregr", label = "retta di regressione", value = FALSE)
                                                ),
                                                column(2,
                                                       textOutput("regr_sp_rregr_interc"),
                                                       textOutput("regr_sp_rregr_pdz")),
                                                column(12),
                                                column(4,
                                                       h4("Intercetta:"),
                                                       h4(HTML("H<SUB>0</SUB>: &beta;<SUB>0</SUB> = 0 <br>
                                                               H<SUB>1</SUB>: &beta;<SUB>0</SUB> &ne; 0")),
                                                       br(),
                                                       
                                                       textOutput("regr_sp_int_stat"),
                                                       textOutput("regr_sp_int_pval"),
                                                       hr(),
                                                       h4("Stima puntuale"),
                                                       textOutput("regr_sp_int_stima"),
                                                       textOutput("regr_sp_int_es"),
                                                       br(),
                                                       h4("Stima per intervallo"),
                                                       textOutput("regr_sp_int_ic_inf"),
                                                       textOutput("regr_sp_int_ic_sup"),
                                                       hr(),
                                                       actionButton("regr_sp_resample1","Ricampiona",style='padding:4px; font-size:100%')
                                                ),
                                                column(8,
                                                       plotOutput("regr_sp_graf_distr")),
                                                column(8),
                                                column(4,
                                                       checkboxInput("regr_sp_pvalue", label = "p-value", value = FALSE)
                                                       ),
                                                column(12,
                                                       hr()),
                                                column(4,
                                                       h4("Pendenza:"),
                                                       h4(HTML("H<SUB>0</SUB>: &beta;<SUB>1</SUB> = 0 <br>
                                                               H<SUB>1</SUB>: &beta;<SUB>1</SUB> &ne; 0")),
                                                       br(),
                                                       textOutput("regr_sp_pen_stat"),
                                                       textOutput("regr_sp_pen_pval"),
                                                       hr(),
                                                       h4("Stima puntuale"),
                                                       textOutput("regr_sp_pen_stima"),
                                                       textOutput("regr_sp_pen_es"),
                                                       br(),
                                                       h4("Stima per intervallo"),
                                                       textOutput("regr_sp_pen_ic_inf"),
                                                       textOutput("regr_sp_pen_ic_sup"),
                                                       hr(),
                                                       actionButton("regr_sp_resample2","Ricampiona",style='padding:4px; font-size:100%')
                                                ),
                                                column(8,
                                                       plotOutput("regr_sp_graf_distr_pen")),
                                                column(8),
                                                column(4,
                                                       checkboxInput("regr_sp_pvalue2", label = "p-value", value = FALSE)
                                                )),
                              
                              tabPanel("Previsione",
                                       column(12,div(textOutput("regr_prev_titolo"),style="font-size:150%;")),
                                       hr(),
                                       column(2,
                                              numericInput("regr_prev_a",label = "Intercetta",value=0)),
                                       column(2,
                                              numericInput("regr_prev_b",label = "Pendenza",value=1)),
                                       column(2,
                                              numericInput("regr_prev_var",label = "Dev. st. errore",value=1)),
                                       column(12,br()),
                                       column(4,
                                              textInput("regr_prev_dis","Disegno sperimentale (punti sperimentali separati da spazio)", "2 4 6 8 10"),
                                              br(),
                                              h5("Matrice sperimentale"),
                                              tableOutput("regr_prev_matrexp"),
                                              actionButton("regr_prev_resample","Ricampiona",style='padding:4px; font-size:100%')),
                                       column(8,
                                              hr(),
                                              plotOutput("regr_prev_graf")),
                                       column(2,
                                              numericInput("regr_prev_x0",label = "Punto previsione",value=0,width = "50%")),
                                       column(4),
                                       
                                       column(2,
                                              checkboxInput("regr_prev_rstim", label = "valore da stimare", value = TRUE)),
                                       column(2,
                                              checkboxInput("regr_prev_rregr", label = "previsione", value = FALSE)),
                                       column(2,
                                              checkboxInput("regr_prev_intconf", label = "intervallo di confidenza", value = FALSE)),
                                       column(12),
                                       column(4),
                                       column(2,h4("Stima puntuale"),
                                              textOutput("regr_prev_stimaprev"),
                                              textOutput("regr_prev_esprev")),
                                       column(4,h4("Stima per intervallo (al 95%)"),
                                              textOutput("regr_prev_icinf"),
                                              textOutput("regr_prev_icsup"))
                                       ),

                              tabPanel("Leverage",
                                       column(12),
                                       hr(),
                                       column(2,
                                              numericInput("regr_lev_a",label = "Intercetta",value=0)),
                                       column(2,
                                              numericInput("regr_lev_b",label = "Pendenza",value=1)),
                                       column(2,
                                              numericInput("regr_lev_var",label = "Dev. st. errore",value=1)),
                                       column(12,br()),
                                       column(4,
                                              textInput("regr_lev_dis","Disegno sperimentale (punti sperimentali separati da spazio)", "2 4 6 8 10"),
                                              br(),
                                              h5("Matrice sperimentale"),
                                              tableOutput("regr_lev_matrexp"),
                                              actionButton("regr_lev_resample","Ricampiona",style='padding:4px; font-size:100%')),
                                       column(8,
                                              plotOutput("regr_lev")
                                              ))

                              )
                  
                  
                  

        )), 

# File --------------------------------------------------------------------
      
      tabItem(tabName = "dispensa",
              fluidPage(
                tabsetPanel(type = "tabs",
                            tabPanel("Glossario",
                                     tags$iframe(style="height:600px; width:100%; scrolling=yes", 
                                                 src="00_Glossario.pdf")),
                            tabPanel("Statistica descrittiva",
                                     tags$iframe(style="height:600px; width:100%; scrolling=yes", 
                                                 src="01_Statistica_descrittiva.pdf")),
                            tabPanel("Statistica inferenziale",
                                     tags$iframe(style="height:600px; width:100%; scrolling=yes", 
                                                 src="02_Statistica_inferenziale.pdf")),
                            tabPanel("Regressione",
                                     tags$iframe(style="height:600px; width:100%; scrolling=yes", 
                                                 src="03_Regressione.pdf")),
                            tabPanel("Anova",
                                     tags$iframe(style="height:600px; width:100%; scrolling=yes", 
                                                 src="04_Anova.pdf"))
                            ))),

      tabItem(tabName = "diapositive",
             fluidPage(
                tabsetPanel(type = "tabs",
                            tabPanel("Statistica descrittiva",
                                     tags$iframe(style="height:600px; width:100%; scrolling=yes", 
                                                 src="01_Statistica_descrittiva_dia.pdf")),
                            tabPanel("Statistica inferenziale",
                                     tags$iframe(style="height:600px; width:100%; scrolling=yes", 
                                                 src="02_Statistica_inferenziale_dia.pdf")),
                            tabPanel("Regressione",
                                     tags$iframe(style="height:600px; width:100%; scrolling=yes", 
                                                 src="03_Regressione_dia.pdf")),
                            tabPanel("Anova",
                                     tags$iframe(style="height:600px; width:100%; scrolling=yes", 
                                                 src="04_Anova_dia.pdf"))
                           
                           
                           )))
)))





ui <- dashboardPage(skin = 'purple',header, sidebar, body,
                    tags$head(HTML("<title>Modunivar</title>"),tags$link(rel = "stylesheet", type = "text/css", href = "tema.css")))





